### ISSUE TITLE
I have no experience in node js - how can I run your script?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tmanderson/ivona-node#4]
I installed it - what next? I tried `node my.js` with your example:

```
/home/vitaly/ivona-node/my.js:1
exports, require, module, __filename, __dirname) {     var ivona = new Ivona({
                                                                       ^
ReferenceError: Ivona is not defined
    at Object.<anonymous> (/home/vitaly/ivona-node/my.js:1:83)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by tmanderson** [comment]
Are you executing the example file via  `$> node example/example`? If you're using this in a project of your own, you should install this via [npm](http://npmjs.org):

`$> npm install ivona-node`

Then in your file `my.js`:

``` JavaScript
var fs = require('fs'),
      Ivona = require('ivona-node');

var ivona = new Ivona({
    accessKey: 'IVONA_ACCESS_KEY',
    secretKey: 'IVONA_SECRET_KEY'
});

ivona.listVoices().on('complete', function(voices) {
    console.log(voices);
});

//  [string] text - the text to be spoken
//  [object] config (optional) - override Ivona request via 'body' value
ivona.createVoice('This is the text that will be spoken.')
    .pipe(fs.createWriteStream('example/test.mp3'));
```

after that `$ > node my.js` should run the script. Be sure that you actually have your IVONA access and secret keys in there.

**Comment by ArMikael** [comment]
Can I set path to .txt file instead of string inside the createVoice() method in some way?

**Comment by tmanderson** [comment]
@ArMikael, you could do this with the the `fs` node module. There's a method [`fs.readFileSync`](https://nodejs.org/api/fs.html#fs_fs_readsync_fd_buffer_offset_length_position) which would allow you to do just what you're asking. For example:

``` js
var Ivona = require('ivona-node');
var fs = require('fs');

var ivona = new Ivona({
    accessKey: 'IVONA_ACCESS_KEY',
    secretKey: 'IVONA_SECRET_KEY'
});

var text = fs.readFileSync('path/to/file.txt', 'utf8');
var toMP3 = fs.createWriteStream('path/to/file.mp3');

ivona.createVoice(text).pipe(toMP3);
```

The important line there was the `var text = fs.readFileSync('path/to/file.txt');` which would load your text into a `Buffer` and can then be given to `createVoice`.

Does that answer your question?

**Comment by ArMikael** [comment]
@tmanderson thanks for answer. I've got an error from buffer.js. 

```
buffer.js:113`
    throw err;
    ^

TypeError: "size" argument must be a number
    at Function.Buffer.allocUnsafe (buffer.js:140:3)
    at Object.fs.readSync (fs.js:718:21)
    at Object.<anonymous> (C:\Dev\tts\ivona.js:16:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by tmanderson** [comment]
@ArMikael I'm sorry about that. I just realized my mistake. It should be:

```js
var text = fs.readFileSync('path/to/file.txt');
```

Note that's **`readFileSync`** and not **`readSync`**

**Comment by nfriacowboy** [comment]
@tmanderson I had the same mistake at my code :P well played 😄
